# Site settings
title: Mayflower Co-op
email: maycoop@shawbiz.ca
copyright_name: Mayflower Co-op
baseurl: ""
url: "http://mayflowercoop.org"
email_username:  maycoop@shawbiz.ca

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
